language: python
python:
  - "3.5"
# pip install dependencies
install:
  - "pip install -r api/requirements.txt"
  - "pip install coveralls"
# command to run tests
env:
  - PYTHONPATH=.
script:
  - nosetests -sv --with-coverage --cover-package=.
after_success:
  - coveralls
