language: python
python:
  - "3.5"
# pip install dependencies
install:
  - "pip install -r api/requirements.txt"
  - "pip install coveralls"
# command to run tests
env:
  - PYTHONPATH=.
script:
  - coverage run --source=api/ api/test_helpers.py && echo PYTHONPATH
after_success:
  - coveralls
